export const menuData = {
  "PIZZE TRADIZIONALI": [
    { name: "AMERICANA", price: 8.5, ingredients: "Pomodoro, fior di latte, wurstel, patatine fritte" },
    { name: "BUFALA", price: 9.5, ingredients: "Pomodoro, fior di latte, bufala, basilico" },
    { name: "CAPRESE", price: 8.5, ingredients: "Pomodoro, fior di latte, bufala, pomodorini, basilico" },
    { name: "CAPRICCIOSA", price: 9, ingredients: "Pomodoro, fior di latte, pro cotto, carciofi, champignon, olive, capperi" },
    { name: "MARINARA", price: 5.5, ingredients: "Doppio pomodoro, aglio, olio extra, origano" },
    { name: "MARGHERITA", price: 6, ingredients: "Pomodoro, fior di latte" },
    { name: "NAPOLI", price: 8, ingredients: "Pomodoro, fior di latte, alici, origano" },
    { name: "PORCINI", price: 8.5, ingredients: "Pomodoro, fior di latte, porcini trifolati" },
    { name: "PRO & FUNGHI", price: 8.5, ingredients: "Pomodoro, fior di latte, pro cotto, champignon" },
    { name: "PRO & CARCIOFI", price: 8.5, ingredients: "Pomodoro, fior di latte, pro cotto, carciofi" },
    { name: "PUGLIESE", price: 7.5, ingredients: "Pomodoro, fior di latte, cipolle rosse" },
    { name: "4 STAGIONI", price: 8.5, ingredients: "Pomodoro, fior di latte, pro cotto, carciofi, olive, champignon" },
    { name: "ROMANA", price: 7.5, ingredients: "Pomodoro, fior di latte, alici, capperi, origano" },
    { name: "SALAMINO", price: 7.5, ingredients: "Pomodoro, fior di latte, spianata" },
    { name: "SICILIANA", price: 8.5, ingredients: "Pomodoro, fior di latte, spianata, olive, capperi, alici, origano" },
    { name: "VERDURE GRILL", price: 9, ingredients: "Pomodoro, fior di latte, melanzane, zucchine, peperoni" },
    { name: "ZOLA", price: 8, ingredients: "Pomodoro, fior di latte, zola" },
    { name: "PRO COTTO", price: 7.5, ingredients: "Pomodoro, fior di latte, pro cotto" },
    { name: "4 FORMAGGI", price: 8, ingredients: "Pomodoro, fior di latte, selezione di formaggi" },
    { name: "FRUTTI DI MARE", price: 10.5, ingredients: "Doppio pomodoro, cozze, gamberetti, calamari, totani, pomodorini, basilico" },
    { name: "MARI & MONTI", price: 9.5, ingredients: "Pomodoro, fior di latte, frutti di mare, porcini" },
    { name: "TONNO", price: 8, ingredients: "Pomodoro, fior di latte, tonno" },
    { name: "TONNO & CIPOLLE", price: 8, ingredients: "Pomodoro, fior di latte, cipolle rosse" },
    { name: "GAMBERETTI", price: 9, ingredients: "Pomodoro, fior di latte, gamberetti" },
    { name: "SALMONE", price: 9, ingredients: "Pomodoro, fior di latte, salmone affumicato" },
    { name: "BRESAOLA", price: 10, ingredients: "Pomodoro, fior di latte, bresaola punta d’anca" },
    { name: "CRUDO", price: 10, ingredients: "Pomodoro, fior di latte, crudo DOP" },
    { name: "SPECK", price: 8, ingredients: "Pomodoro, fior di latte, speck tirolese" },
    { name: "SALAME", price: 8, ingredients: "Pomodoro, fior di latte, salame nostrano" },
    { name: "PANCETTA", price: 8, ingredients: "Pomodoro, fior di latte, pancetta coppata" }
  ],
  "FOCACCIA / CALZONI": [
    { name: "FOCACCIA LISCIA", price: 4.5, ingredients: "Olio, sale, rosmarino, grana" },
    { name: "FOCACCIA CAPRI", price: 8, ingredients: "Grana, olio extra, pomodorini, bufala, origano" },
    { name: "FOCACCIA FRESCA", price: 9, ingredients: "Crudo, rucola, grana, stracciatella" },
    { name: "CALZONE LISCIO", price: 7.5, ingredients: "Pomodoro, fior di latte, pro cotto, origano" },
    { name: "CALZONE FARCITO", price: 9, ingredients: "Pomodoro, carciofi, pro cotto, champignon, olive, capperi" }
  ],
  "PIZZE SPECIALI": [
    { name: "PARTENOPEA", price: 9, ingredients: "Base bianca, friarielli, salsiccia, provola affumicata" },
    { name: "PISTACCHIELLA", price: 9.5, ingredients: "Base bianca, mortadella, stracciata pugliese, granella di pistacchio" },
    { name: "CARBONARA", price: 10.5, ingredients: "Guanciale dopo cottura, pecorino romano, fior di latte, crema carbonara" },
    { name: "NORMA & NDUJA", price: 9, ingredients: "Base rossa, melanzane fritte, ricotta salata, nduja di Spilinga" },
    { name: "3P", price: 9, ingredients: "Base bianca, provola, pancetta, patate rustiche al rosmarino" },
    { name: "TARTUFELLA", price: 10, ingredients: "Base bianca, salsiccia, porcini, crema al tartufo" },
    { name: "CRUÒ", price: 11, ingredients: "Base pomodoro giallo siciliano, fior di latte, burrata, crudo DOP, granella di nocciole, riduzione al balsamico" },
    { name: "YELLOW MELLOW", price: 7.5, ingredients: "Pomodoro giallo siciliano, fior di latte, basilico" },
    { name: "GOURMET", price: 9.5, ingredients: "Base rossa, pomodorini confit, stracciata pugliese, basilico" },
    { name: "PARMIGIANA", price: 9, ingredients: "Pomodoro, fior di latte, pro cotto, melanzane, grana" },
    { name: "AMATRICIANA", price: 9.5, ingredients: "Pomodoro, fior di latte, guanciale dopo cottura, cipolle caramellate, pecorino" },
    { name: "MARCHETTARA", price: 9.5, ingredients: "Base bianca, pomodoro secco, pesto di basilico, zucchine, tarallo sbriciolato" },
    { name: "CACIO & GAMBERI", price: 10, ingredients: "Base bianca, pecorino, pepe, gamberi, confit" },
    { name: "BURRATINA", price: 10, ingredients: "Base rossa, burrata, alici, zest di limone" },
    { name: "TONNARELLA", price: 9, ingredients: "Pomodoro giallo siciliano, fior di latte, formaggio affumicato, tonno" },
    { name: "CALABRA", price: 9, ingredients: "Pomodoro, fior di latte, spianata, nduja, provola affumicata" }
  ],
  "HAMBURGER": [
    { name: "CLASSIC BURGER", price: 10, ingredients: "Carne bovino, insalata, pomodoro, ketchup, pancetta" },
    { name: "CHEESEBURGER", price: 10, ingredients: "Carne bovino, insalata, pomodori, edamer, pancetta, salsa burger" },
    { name: "CARBONARO", price: 11, ingredients: "Carne manzo, pancetta, crema carbonara, insalata" },
    { name: "MATRICIANO", price: 11, ingredients: "Carne manzo, cipolla caramellata, pancetta, formaggio affumicato" },
    { name: "MARCHETTARO", price: 11, ingredients: "Burger manzo, pomodoro secco, zucchine scapece, stracciata" },
    { name: "CALABRO", price: 11, ingredients: "Burger manzo, spianata croccante, salsa piccante, formaggio affumicato" },
    { name: "PORCINO", price: 11, ingredients: "Burger manzo, crema funghi, formaggio affumicato, pancetta" }
  ],
  "FRITTI": [
    { name: "Patate fritte + salsa a scelta", price: 3 },
    { name: "Crocchette di patate (8 pz) + salsa", price: 4 },
    { name: "Mozzarelline (8 pz) + salsa", price: 4 },
    { name: "Olive ascolane (8 pz) + salsa", price: 4 },
    { name: "Jalapeno (5 pz) + salsa", price: 4 }
  ],
  "VARIAZIONI / EXTRA": [
    { name: "Burratina", price: 2.5 },
    { name: "Mozzarella di bufala", price: 4 },
    { name: "Stracciatella", price: 2.5 },
    { name: "Mozzarella no latte", price: 2 },
    { name: "Affettati", price: 1.5 },
    { name: "Formaggi", price: 1.5 },
    { name: "Cipolle caramellate", price: 1 },
    { name: "Confit", price: 1 },
    { name: "Porcini", price: 2.5 },
    { name: "Verdure", price: 2 },
    { name: "Tonno", price: 1.5 },
    { name: "Acciughe", price: 1.5 },
    { name: "Gamberi", price: 3 },
    { name: "Salmone", price: 3 },
    { name: "Impasti speciali", price: "+2" },
    { name: "Pizza mini", price: 1 },
    { name: "Altro", price: 1 },
    { name: "Base no glutine", price: 2 }
  ],
  "BEVANDE": [
    { name: "Coca Cola", price: 2.5 },
    { name: "Coca Zero", price: 2.5 },
    { name: "Fanta", price: 2.5 },
    { name: "Sprite", price: 2.5 },
    { name: "Soda/Tonica", price: 3.5 },
    { name: "Thé pesca/limone", price: 3.5 },
    { name: "COCA COLA 1.5 L", price: 3 },
    { name: "ACQUA 0.5 L", price: 1 },
    { name: "PROSECCO (bottiglia)", price: 15 },
    { name: "Forst 33 cl", price: 2.5 },
    { name: "Ichnusa 33 cl", price: 2.5 },
    { name: "Forst 66 cl", price: 3.5 },
    { name: "Ichnusa 66 cl", price: 3.5 }
  ]
};
